
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class customer_home extends javax.swing.JFrame {

    /**
     * Creates new form customer_home
     */
    String userid;
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    public customer_home() {
        initComponents();
        conn = connect.ConnectDB();
        CurrentDate();
        customerupdate();
        updateTable();
    }
    protected void customerID(String email)
    {
        this.userid = email;
        customerupdate();
    }
    private void customerupdate()
    {
        String sql="Select  *   from customers_info where email = '"+userid+"';";
     
  try{
    pst =conn.prepareStatement(sql);
    rs=pst.executeQuery();
    //pst.execute();
    if(rs.next()){
    String name=rs.getString("name");
    customer_name.setText(name);
    String balance=rs.getString("balance");
    customer_balance.setText(balance);
    customer_balance.setEditable(false);
    String sex=rs.getString("sex");
    customer_sex.setSelectedItem(sex);
    String age=rs.getString("age");
    customer_age.setText(age);
    String address=rs.getString("address");
    customer_address.setText(address);
    String city=rs.getString("city");
    customer_city.setText(city);
    String postal=rs.getString("postal");
    customer_postal.setText(postal);
    String phone=rs.getString("phone");
    customer_phone.setText(phone);
    String email=rs.getString("email");
    customer_email.setText(email);
    customer_email.setEditable(false);
    String password=rs.getString("password");
    customer_password.setText(password);
    String acc_type=rs.getString("acc_type");
    customer_acc_type.setSelectedItem(acc_type);
    String nid=rs.getString("nid");
    customer_nid.setText(nid);
    byte[] imagedata =rs.getBytes("image");
    format  = new ImageIcon(imagedata);
    customer_image_preview.setIcon(format);
    }        
    }catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }finally {
try{
  rs.close();
      pst.close();
     
  }
  catch(Exception e) {
                   }
      } 
    }
    private void updateTable()
    {
        String sql="select * from cus_tranc where username = '"+userid+"';";
        try{ 
   
            pst =conn.prepareStatement(sql);
            //pst.setString(1,customer_tranc_search.getText());
            //pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            //pst.execute();
            customer_tranc.setModel(DbUtils.resultSetToTableModel(rs));
            }catch(Exception e)
                {
                       JOptionPane.showMessageDialog(null, e);

                }finally {
            try{
              rs.close();
                  pst.close();

              }
              catch(Exception e) {
                               }
                  }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        customer_edit = new javax.swing.JButton();
        customer_refresh = new javax.swing.JButton();
        customer_pdf = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        customer_tranc_search = new javax.swing.JTextField();
        customer_search_button = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        customer_name = new javax.swing.JTextField();
        customer_balance = new javax.swing.JTextField();
        customer_sex = new javax.swing.JComboBox<>();
        customer_age = new javax.swing.JTextField();
        customer_address = new javax.swing.JTextField();
        customer_city = new javax.swing.JTextField();
        customer_postal = new javax.swing.JTextField();
        customer_phone = new javax.swing.JTextField();
        customer_email = new javax.swing.JTextField();
        customer_nid = new javax.swing.JTextField();
        customer_password = new javax.swing.JPasswordField();
        customer_acc_type = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        customer_tranc = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        customer_image_preview = new javax.swing.JLabel();
        customer_attach = new javax.swing.JButton();
        customer_image_path = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        request_card = new javax.swing.JButton();
        request_check = new javax.swing.JButton();
        sign_out = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Lbl_time = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Command", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(0, 0, 204)))); // NOI18N

        customer_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Files-Edit-file-icon (1).png"))); // NOI18N
        customer_edit.setText("Edit");
        customer_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_editActionPerformed(evt);
            }
        });

        customer_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Refresh-icon (1).png"))); // NOI18N
        customer_refresh.setText("Refresh");
        customer_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_refreshActionPerformed(evt);
            }
        });

        customer_pdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PDF-download-icon.png"))); // NOI18N
        customer_pdf.setText("PDF");
        customer_pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_pdfActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print-icon.png"))); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(customer_pdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customer_refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customer_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(customer_edit)
                .addGap(39, 39, 39)
                .addComponent(customer_refresh)
                .addGap(28, 28, 28)
                .addComponent(customer_pdf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        jLabel1.setText("Search:");

        customer_tranc_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_tranc_searchActionPerformed(evt);
            }
        });
        customer_tranc_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                customer_tranc_searchKeyReleased(evt);
            }
        });

        customer_search_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Windows-Magnifier-icon.png"))); // NOI18N
        customer_search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_search_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(customer_tranc_search, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(customer_search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(customer_tranc_search)
                    .addComponent(customer_search_button, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Account Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("C790-Roman-Smc", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        customer_sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        customer_acc_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "Savings", "Primary" }));

        jLabel3.setText("Name:");

        jLabel4.setText("Balance(initial):");

        jLabel5.setText("Sex:");

        jLabel6.setText("Age:");

        jLabel7.setText("Address:");

        jLabel8.setText("City:");

        jLabel9.setText("Postal Code:");

        jLabel10.setText("Phone:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Email:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Password:");

        jLabel13.setText("NID");

        jLabel14.setText("Account Type:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customer_acc_type, 0, 83, Short.MAX_VALUE)
                    .addComponent(customer_password)
                    .addComponent(customer_nid)
                    .addComponent(customer_email)
                    .addComponent(customer_phone)
                    .addComponent(customer_postal)
                    .addComponent(customer_city)
                    .addComponent(customer_address)
                    .addComponent(customer_age)
                    .addComponent(customer_balance)
                    .addComponent(customer_name, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(customer_sex, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customer_balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(customer_sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customer_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customer_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customer_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customer_postal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customer_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customer_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customer_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customer_nid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customer_acc_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)))
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Transaction", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Anklepants", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        customer_tranc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(customer_tranc);

        jDesktopPane1.setLayer(customer_image_preview, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customer_image_preview, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customer_image_preview, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );

        customer_attach.setText("Attach");
        customer_attach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_attachActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Request", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        request_card.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        request_card.setText("Request for a Card");
        request_card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                request_cardActionPerformed(evt);
            }
        });

        request_check.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        request_check.setText("Request For a Check");
        request_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                request_checkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(request_check, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(request_card, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(request_card)
                .addGap(41, 41, 41)
                .addComponent(request_check)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(customer_attach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customer_image_path, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customer_attach)
                            .addComponent(customer_image_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        sign_out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SignOut-icon.png"))); // NOI18N
        sign_out.setText("SignOut");
        sign_out.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sign_out.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sign_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_outActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Help");

        jMenuItem1.setText("About us");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);
        jMenu4.add(jSeparator1);

        jMenuItem2.setText("Help Desk");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        jMenu3.setForeground(new java.awt.Color(204, 0, 153));
        jMenu3.setText("Date");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu3);

        Lbl_time.setForeground(new java.awt.Color(204, 0, 153));
        Lbl_time.setText("Time");
        Lbl_time.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(Lbl_time);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 838, Short.MAX_VALUE)
                        .addComponent(sign_out)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sign_out)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        About_us p=new About_us();
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try                                      //try statement
        {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "C:\\Users\\User\\Documents\\NetBeansProjects\\bank\\Ask Frequently Question.pdf");   //open the file chart.pdf

        } catch (Exception e)                    //catch any exceptions here
        {
            JOptionPane.showMessageDialog(null,"Error");  //print the error
        }finally {
            try{
                rs.close();
                pst.close();
                //conn.close();
            }
            catch(Exception e) {
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void sign_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_outActionPerformed
        // TODO add your handling code here:
        try{
                    rs.close();
                        pst.close();
                       conn.close();
                    }
                    catch(Exception e) {
                                     }

                          customers_login a = new customers_login();
                      a.setVisible(true);
                      this.dispose();
    }//GEN-LAST:event_sign_outActionPerformed

    private void customer_tranc_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_tranc_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customer_tranc_searchActionPerformed

    private void customer_attachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_attachActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        filename=f.getAbsolutePath();
        customer_image_path.setText(filename);
        
        try {
            File customer_image_preview = new File (filename);
            FileInputStream fis=new FileInputStream(customer_image_preview);
            ByteArrayOutputStream bos =new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for(int readNum; (readNum=fis.read(buf))!=-1; ){
                
                bos.write(buf,0,readNum);
            }
            
            customer_image=bos.toByteArray();
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, customer_image_preview);
        }
    }//GEN-LAST:event_customer_attachActionPerformed

    private void customer_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_editActionPerformed
        // TODO add your handling code here:
        String sql="UPDATE customers_info SET name = ?, balance = ?, sex = ?, age = ?, address = ?, city = ?, postal = ?, phone = ?, password = ?, nid = ?, acc_type = ?, image = ? WHERE  email = ?";
         try{
    pst =conn.prepareStatement(sql);
    pst.setString(1, customer_name.getText());
    pst.setString(2, customer_balance.getText());
    pst.setString(3, customer_sex.getSelectedItem().toString());
    pst.setString(4, customer_age.getText());
     pst.setString(5, customer_address.getText());
    pst.setString(6, customer_city.getText());
    pst.setString(7, customer_postal.getText());
    pst.setString(8, customer_phone.getText());
     pst.setString(9, customer_password.getText());
     pst.setString(10, customer_nid.getText());
     pst.setString(11, customer_acc_type.getSelectedItem().toString());
     pst.setBytes(12, customer_image);
     pst.setString(13, customer_email.getText());
   
   
    
   // rs=pst.executeQuery()txt_dob;
    pst.execute();
    customerupdate();
    JOptionPane.showMessageDialog(null, "Updated");
    //administrator_windows_JForm s = new administrator_windows_JForm();
    //s.setVisible(true);
    
    
    
    
            
    }catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }finally {
try{
  rs.close();
      pst.close();
    // conn.close();
  }
  catch(Exception e) {
                   }
               }
    }//GEN-LAST:event_customer_editActionPerformed

    private void customer_tranc_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customer_tranc_searchKeyReleased
        // TODO add your handling code here:
        try{ 
        String sql="select * from cus_tranc where types like '%"+customer_tranc_search.getText()+"%' and username = '"+userid+"'";
   
            pst =conn.prepareStatement(sql);
            //pst.setString(1,customer_tranc_search.getText());



            //pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            //pst.execute();
            customer_tranc.setModel(DbUtils.resultSetToTableModel(rs));
            }catch(Exception e)
                {
                       JOptionPane.showMessageDialog(null, e);

                }finally {
            try{
              rs.close();
                  pst.close();

              }
              catch(Exception e) {
                               }
                  }
    }//GEN-LAST:event_customer_tranc_searchKeyReleased

    private void customer_search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_search_buttonActionPerformed
        // TODO add your handling code here:
        try{ 
        String sql="select * from cus_tranc where types like '%"+customer_tranc_search.getText()+"%' and username = '"+userid+"'";
   
            pst =conn.prepareStatement(sql);
            //pst.setString(1,customer_tranc_search.getText());



            //pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            //pst.execute();
            customer_tranc.setModel(DbUtils.resultSetToTableModel(rs));
            }catch(Exception e)
                {
                       JOptionPane.showMessageDialog(null, e);

                }finally {
            try{
              rs.close();
                  pst.close();

              }
              catch(Exception e) {
                               }
                  }
    }//GEN-LAST:event_customer_search_buttonActionPerformed

    private void customer_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_refreshActionPerformed
        // TODO add your handling code here:
        CurrentDate();
        customerupdate();
        updateTable();
    }//GEN-LAST:event_customer_refreshActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Security Bank");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}");
        try {
            customer_tranc.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
            //table.print(JTable.PrintMode.FIT_WIDTH, header, null);
           // jTable1_pumpdata.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }  finally {
try{
  rs.close();
      pst.close();
     //conn.close();
  }
  catch(Exception e) {
                   }
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void customer_pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_pdfActionPerformed
        // TODO add your handling code here:
        Calendar cal = new GregorianCalendar();
  int month = cal.get(Calendar.MONTH);
  int year = cal.get(Calendar.YEAR);
  int day = cal.get(Calendar.DAY_OF_MONTH);
  //String date1 = null;
  //jMenu3.setText("                                                                      Date : "   + day + "/" + (month + 1) + "/" + year);
  //System.out.println("Current date : " + day + "/" + (month + 1) + "/" + year);
        try                                      //try statement     
     {   
           
           Document document=new Document();
        PdfWriter.getInstance(document,new FileOutputStream("Customer Details.pdf"));

document.open();
//document.addSubject("hhhhhhhhhhhh");     
   //document.addHeader(date1,"hhii"); 
   //document.addCreationDate();
 Image image1 = Image.getInstance("C:\\Users\\User\\Documents\\NetBeansProjects\\bank\\src\\images\\SECURITY-BANK.png");
 //  image1.scaleAbsolute(300,300);
document.add(image1);



//Image image2 = Image.getInstance(admin_image);
//image2.scaleAbsolute(20,20);
//document.add(image2);
 document.add(new Paragraph((new Chunk("Security Bank                                         "   + day + "/" + (month + 1) + "/" + year, FontFactory.getFont(FontFactory.HELVETICA, 18, Font.BOLD)))));
 document.add(new Paragraph("Secure Bank Management System"));
 document.add(new Paragraph("*************************************************************************************************"));
PdfPTable table=new PdfPTable(2);
PdfPCell cell = new PdfPCell (new Paragraph ("Account Information Details"));
cell.setColspan (8);
cell.setHorizontalAlignment (Element.ALIGN_CENTER);
cell.setBackgroundColor(BaseColor.GREEN);
cell.setPadding (10.0f);
table.addCell (cell);
cell = new PdfPCell (new Paragraph ("FIELD"));
cell.setHorizontalAlignment (Element.ALIGN_CENTER);
cell.setBackgroundColor (BaseColor.LIGHT_GRAY);
cell.setPadding (10.0f);
table.addCell (cell);
cell = new PdfPCell (new Paragraph ("Details"));
cell.setHorizontalAlignment (Element.ALIGN_CENTER);
cell.setBackgroundColor (BaseColor.LIGHT_GRAY);
cell.setPadding (10.0f);
table.addCell (cell);
table.addCell("Name");
table.addCell(customer_name.getText());
table.addCell("Balance");
table.addCell(customer_balance.getText());
table.addCell("Sex");
table.addCell(customer_sex.getSelectedItem().toString());
table.addCell("Age");
table.addCell(customer_age.getText());
table.addCell("Address");
table.addCell(customer_address.getText());
table.addCell("City");
table.addCell(customer_city.getText());
table.addCell("Postal Code");
table.addCell(customer_postal.getText());
table.addCell("Phone");
table.addCell(customer_phone.getText());
table.addCell("Email");
table.addCell(customer_email.getText());
table.addCell("National ID");
table.addCell(customer_nid.getText());
table.addCell("Account Type");
table.addCell(customer_acc_type.getSelectedItem().toString());


document.add(table);

        
    document.add(new Paragraph(""));   
document.add(new Paragraph("© 2016-2017 Security Bank. All right reserved."));
  



      //  document.add(new Paragraph(new Date().toString()));
       
document.close(); 
     JOptionPane.showMessageDialog(null, "Report Saved");
     
     } catch (Exception e)                    //catch any exceptions here
       {
            JOptionPane.showMessageDialog(null,"Not Saved");  //print the error
       }
        
          finally {
try{
  rs.close();
   pst.close();
     //conn.close();
  }
  catch(Exception e) {
                   }
      }
    }//GEN-LAST:event_customer_pdfActionPerformed

    private void request_cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_request_cardActionPerformed
        // TODO add your handling code here:
        String sql="UPDATE customers_info SET card = 0 WHERE  email = ?";
         try{
    pst =conn.prepareStatement(sql);
     pst.setString(1, customer_email.getText());
   
   
    
   // rs=pst.executeQuery()txt_dob;
    pst.execute();
    customerupdate();
    JOptionPane.showMessageDialog(null, "Updated");
    //administrator_windows_JForm s = new administrator_windows_JForm();
    //s.setVisible(true);
    
    
    
    
            
    }catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }finally {
try{
  rs.close();
      pst.close();
    // conn.close();
  }
  catch(Exception e) {
                   }
               }
    }//GEN-LAST:event_request_cardActionPerformed

    private void request_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_request_checkActionPerformed
        // TODO add your handling code here:
        String sql="UPDATE customers_info SET checkbook = 0 WHERE  email = ?";
         try{
    pst =conn.prepareStatement(sql);
     pst.setString(1, customer_email.getText());
   
   
    
   // rs=pst.executeQuery()txt_dob;
    pst.execute();
    customerupdate();
    JOptionPane.showMessageDialog(null, "Updated");
    //administrator_windows_JForm s = new administrator_windows_JForm();
    //s.setVisible(true);
    
    
    
    
            
    }catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }finally {
try{
  rs.close();
      pst.close();
    // conn.close();
  }
  catch(Exception e) {
                   }
               }
    }//GEN-LAST:event_request_checkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer_home().setVisible(true);
            }
        });
    }
    
    public void CurrentDate(){
  
  Calendar cal = new GregorianCalendar();
  int month = cal.get(Calendar.MONTH);
  int year = cal.get(Calendar.YEAR);
  int day = cal.get(Calendar.DAY_OF_MONTH);
  jMenu3.setText("Current date : "   + day + "/" + (month + 1) + "/" + year);
  //System.out.println("Current date : "  + day + "/" + (month + 1) + "/" + year);
  
     int second = cal.get(Calendar.SECOND);
     int minute = cal.get(Calendar.MINUTE);
     int hour = cal.get(Calendar.HOUR);
 Lbl_time.setText("Current time is  "+hour+" : "+minute+" : "+second);
     
      //System.out.println("Current time is  "+hour+" : "+minute+" : "+second);
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Lbl_time;
    private javax.swing.JComboBox<String> customer_acc_type;
    private javax.swing.JTextField customer_address;
    private javax.swing.JTextField customer_age;
    private javax.swing.JButton customer_attach;
    private javax.swing.JTextField customer_balance;
    private javax.swing.JTextField customer_city;
    private javax.swing.JButton customer_edit;
    private javax.swing.JTextField customer_email;
    private javax.swing.JTextField customer_image_path;
    private javax.swing.JLabel customer_image_preview;
    private javax.swing.JTextField customer_name;
    private javax.swing.JTextField customer_nid;
    private javax.swing.JPasswordField customer_password;
    private javax.swing.JButton customer_pdf;
    private javax.swing.JTextField customer_phone;
    private javax.swing.JTextField customer_postal;
    private javax.swing.JButton customer_refresh;
    private javax.swing.JButton customer_search_button;
    private javax.swing.JComboBox<String> customer_sex;
    private javax.swing.JTable customer_tranc;
    private javax.swing.JTextField customer_tranc_search;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton request_card;
    private javax.swing.JButton request_check;
    private javax.swing.JButton sign_out;
    // End of variables declaration//GEN-END:variables
private ImageIcon format = null;

String filename=null;
int s=0;
//byte[] admin_image = null;
byte[] customer_image = null;
//byte[] loan_image = null;
//byte[] staff_image = null;

}
